# Generated by Django 6.0.2 on 2026-02-20 21:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parlour', '0011_product_purchase_cost_product_supplier_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='💰', max_length=10)),
                ('color', models.CharField(default='#c9a84c', help_text='Hex color e.g. #c9a84c', max_length=7)),
                ('is_stock_category', models.BooleanField(default=False, help_text='Mark this if the category is for buying stock/products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Budget Category',
                'verbose_name_plural': 'Budget Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_capital', models.DecimalField(decimal_places=2, help_text='Total money available this month (KSH)', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monthly Budget',
                'verbose_name_plural': 'Monthly Budgets',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('receipt_note', models.TextField(blank=True, help_text='Optional: receipt number or extra notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.budgetcategory')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.monthlybudget')),
            ],
            options={
                'verbose_name': 'Expense',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapitalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('in', 'Capital In'), ('out', 'Capital Out')], max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_entries', to='finance.monthlybudget')),
            ],
            options={
                'verbose_name': 'Capital Entry',
                'verbose_name_plural': 'Capital Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_at_alert', models.PositiveIntegerField()),
                ('estimated_restock_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated: purchase_cost × restock_qty_needed', max_digits=12, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_alerts', to='parlour.product')),
            ],
            options={
                'verbose_name': 'Restock Alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.budgetcategory')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.monthlybudget')),
            ],
            options={
                'verbose_name': 'Budget Allocation',
                'unique_together': {('budget', 'category')},
            },
        ),
    ]
