# Generated by Django 6.0.2 on 2026-02-08 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('delivery_address', models.TextField()),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('hoodies', 'Hoodies'), ('sweatpants', 'Sweatpants'), ('socks', 'Socks'), ('shorts', 'Shorts'), ('shirts', 'Shirts')], max_length=20)),
                ('image', models.ImageField(upload_to='products/')),
                ('available_sizes', models.CharField(help_text='Comma-separated sizes (e.g., S,M,L,XL)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(blank=True, max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlour.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlour.product')),
            ],
        ),
    ]
