# Generated by Django 6.0.2 on 2026-02-09 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0003_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(default="Hoka's Parlour Main Store, 123 Fashion Street", max_length=300)),
                ('pickup_date', models.DateField(default=django.utils.timezone.now, help_text='Pickup date for all orders')),
                ('pickup_time', models.TimeField(default='22:00:00', help_text='Pickup time (e.g., 10:00 PM)')),
                ('pickup_days_info', models.TextField(default='Monday - Saturday', help_text='Pickup days information')),
                ('store_phone', models.CharField(default='+254 700 000 000', max_length=20)),
                ('store_email', models.EmailField(default='hokasparlour@gmail.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='emailotp',
            options={'verbose_name': 'Email OTP', 'verbose_name_plural': 'Email OTPs'},
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
