# Generated by Django 6.0.2 on 2026-02-17 20:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0005_orderhistory_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name for the ad', max_length=200)),
                ('ad_type', models.CharField(choices=[('single_image', 'Single Image'), ('multi_image', 'Multiple Images (Carousel)'), ('video', 'Video')], default='single_image', max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'All Visitors'), ('new', 'New Visitors Only'), ('returning', 'Returning Visitors')], default='all', max_length=20)),
                ('single_image', models.ImageField(blank=True, help_text='Upload for single image ad', null=True, upload_to='ads/single/')),
                ('video', models.FileField(blank=True, help_text='Upload video (MP4, WebM, OGG)', null=True, upload_to='ads/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])])),
                ('video_poster', models.ImageField(blank=True, help_text='Poster image for video', null=True, upload_to='ads/posters/')),
                ('autoplay', models.BooleanField(default=False, help_text='Autoplay video (muted)')),
                ('loop', models.BooleanField(default=True, help_text='Loop video')),
                ('headline', models.CharField(blank=True, help_text='Main headline (optional)', max_length=200)),
                ('subheadline', models.CharField(blank=True, help_text='Subheadline (optional)', max_length=300)),
                ('button_text', models.CharField(blank=True, default='Shop Now', max_length=50)),
                ('button_url', models.URLField(blank=True, help_text='URL when ad is clicked')),
                ('button_color', models.CharField(default='#667eea', help_text='Button color (hex)', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_mobile', models.BooleanField(default=True)),
                ('show_on_tablet', models.BooleanField(default=True)),
                ('show_on_desktop', models.BooleanField(default=True)),
                ('background_color', models.CharField(blank=True, help_text='Background color (hex)', max_length=20)),
                ('text_color', models.CharField(default='#ffffff', help_text='Text color (hex)', max_length=20)),
                ('overlay_opacity', models.FloatField(default=0.3, help_text='Overlay opacity (0-1)')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('clicks', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/multi/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_images', to='parlour.advertisement')),
            ],
            options={
                'verbose_name': 'Ad Image',
                'verbose_name_plural': 'Ad Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlour.advertisement')),
            ],
            options={
                'indexes': [models.Index(fields=['session_key', 'advertisement'], name='parlour_adi_session_589ca6_idx')],
            },
        ),
    ]
