# Generated by Django 6.0.2 on 2026-02-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0006_advertisement_adimage_adimpression'),
    ]

    operations = [
        migrations.AddField(
            model_name='adimpression',
            name='clicked',
            field=models.BooleanField(default=False),
        ),
    ]
