# Generated by Django 6.0.2 on 2026-02-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0009_mpesapayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_type',
            field=models.CharField(choices=[('ready', 'Ready Stock'), ('warehouse', 'Warehouse Stock')], default='ready', help_text='Select where the product is stocked', max_length=20),
        ),
    ]
