# Generated by Django 6.0.2 on 2026-02-20 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0010_product_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[Ready Stock] How much YOU paid to buy this item for resale.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[Warehouse Stock] How much YOU pay the supplier per item when sourcing.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='autoplay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='background_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='button_color',
            field=models.CharField(default='#667eea', max_length=20),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='button_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='headline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='loop',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='overlay_opacity',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='single_image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/single/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='subheadline',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ads/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])]),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='ads/posters/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price (what the customer pays)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=1, help_text='[Ready Stock] Number of items you currently have. Warehouse stock ignores this.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_type',
            field=models.CharField(choices=[('ready', 'Ready Stock'), ('warehouse', 'Warehouse Stock')], default='ready', help_text='Ready = you own the stock. Warehouse = source after order.', max_length=20),
        ),
    ]
