# Generated by Django 4.2.28 on 2026-03-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0015_color_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='pickup_days_info',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='pickup_time',
        ),
        migrations.AddField(
            model_name='storesettings',
            name='ready_delivery_days',
            field=models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday', help_text='Days next-day delivery is available (comma-separated)', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='ready_delivery_time',
            field=models.TimeField(default='10:00:00', help_text='What time ready stock orders are delivered the next day'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='warehouse_delivery_time',
            field=models.TimeField(default='10:00:00', help_text='What time warehouse stock orders are delivered on Friday'),
        ),
    ]
