# Generated by Django 4.2.28 on 2026-03-03 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0016_remove_storesettings_pickup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_category',
            field=models.CharField(choices=[('main', 'Main (Homepage Hero)'), ('banner', 'Banner'), ('sidebar', 'Sidebar'), ('popup', 'Popup'), ('footer', 'Footer')], default='main', help_text='Where this ad appears on the site', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='link_type',
            field=models.CharField(choices=[('external', 'External URL'), ('product', 'Internal Product')], default='external', help_text='External = any URL. Internal = link directly to a product page.', max_length=10),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='linked_product',
            field=models.ForeignKey(blank=True, help_text='Used when link type is Internal Product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='parlour.product'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='product_category',
            field=models.ForeignKey(blank=True, help_text='Show this ad only to visitors browsing this product category. Leave blank to show to all.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='parlour.category'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='button_url',
            field=models.URLField(blank=True, help_text='Used when link type is External'),
        ),
    ]
