# Generated by Django 6.0.3 on 2026-03-08 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0017_advertisement_ad_category_advertisement_link_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Link to the final Order created after successful payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to='parlour.order'),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='order_details',
            field=models.JSONField(blank=True, help_text='Stores a snapshot of the cart and customer details at the time of payment initiation.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
