# Generated by Django 6.0.3 on 2026-03-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0018_mpesapayment_order_mpesapayment_order_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp_joined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_popup_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
