# Generated by Django 6.0.3 on 2026-03-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0019_profile_whatsapp_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='anchor_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Crossed-out 'original' price shown to all users. Auto-calculated as price × 1.20 if left blank.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Promo price for users with a valid agent code (first 5 products). Auto-calculated as price - (profit × 10%) if left blank.', max_digits=10, null=True),
        ),
    ]
