# Generated by Django 6.0.3 on 2026-03-14 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0020_product_anchor_price_product_discount_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='promo_popup_shown',
            field=models.BooleanField(default=False, help_text='True after the promo code popup has been shown once on signup'),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, help_text='Auto-generated on approval. e.g. HOKA-AB12', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('mpesa_number', models.CharField(blank=True, help_text='M-Pesa number for commission payouts', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Why do you want to become an agent?')),
                ('total_referrals', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromoUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_purchases_count', models.PositiveIntegerField(default=0, help_text='Number of products bought at promo price so far')),
                ('is_active', models.BooleanField(default=True, help_text='False when 5 products have been purchased')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_usages', to='parlour.agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promousage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
