# Generated by Django 6.0.3 on 2026-03-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0021_profile_promo_popup_shown_agent_promousage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Auto-generated from your username on approval. Can be changed by admin. e.g. JOHN-AB12', max_length=20, unique=True),
        ),
    ]
