# Generated by Django 6.0.2 on 2026-03-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0022_alter_agent_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_promo_popup',
            field=models.BooleanField(default=False, help_text='True when user should see the promo popup on next page load'),
        ),
    ]
