# Generated by Django 6.0.3 on 2026-03-18 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0023_profile_show_promo_popup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='intended_stock_type',
            field=models.CharField(choices=[('ready', 'Ready Stock'), ('warehouse', 'Warehouse Stock')], default='ready', help_text="Set this to define how this product is stocked. 'Ready' will auto-switch to warehouse when depleted and back when restocked.", max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_type',
            field=models.CharField(choices=[('ready', 'Ready Stock'), ('warehouse', 'Warehouse Stock')], default='ready', help_text='Current active stock type. Auto-managed — set intended_stock_type instead.', max_length=20),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='parlour.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
