# Generated by Django 6.0.3 on 2026-03-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0024_product_intended_stock_type_alter_product_stock_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='intended_stock_type',
            field=models.CharField(choices=[('ready', 'Ready Stock'), ('warehouse', 'Warehouse Stock')], default='ready', help_text="Admin's intended stock type. Ready stock auto-switches to warehouse when depleted and back when restocked.", max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_type',
            field=models.CharField(choices=[('ready', 'Ready Stock'), ('warehouse', 'Warehouse Stock')], default='ready', help_text='Current active stock type. Auto-managed by the system — edit intended_stock_type instead.', max_length=20),
        ),
    ]
