# Generated by Django 6.0.2 on 2026-03-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0024_wishlist'),
        ('parlour', '0025_alter_product_intended_stock_type_and_more'),
    ]

    operations = [
    ]
