# Generated by Django 6.0.3 on 2026-03-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0025_alter_product_intended_stock_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], default='U', max_length=1),
        ),
    ]
