# Generated by Django 6.0.2 on 2026-03-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0026_category_gender_product_gender'),
        ('parlour', '0026_merge_20260318_2342'),
    ]

    operations = [
    ]
