# Generated by Django 6.0.3 on 2026-04-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0028_profile_age_profile_gender_userpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
