# Generated by Django 6.0.3 on 2026-04-09 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0029_profile_whatsapp_number_profile_whatsapp_otp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('order', 'Order Inquiry'), ('return', 'Return / Exchange'), ('payment', 'Payment Issue'), ('delivery', 'Delivery Issue'), ('product', 'Product Question'), ('other', 'Other')], default='other', max_length=100)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('receipt_note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='unread', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes visible only to admin')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
