# Generated by Django 6.0.2 on 2026-04-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0027_merge_20260323_1627'),
        ('parlour', '0030_contactmessage'),
    ]

    operations = [
    ]
