# Generated by Django 6.0.3 on 2026-04-16 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0032_alter_storesettings_pickup_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, help_text='The store this product belongs to. Leave blank for Qunimart default store.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='parlour.store'),
        ),
    ]
