# Generated by Django 6.0.3 on 2026-04-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0033_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Product visible on site'),
        ),
    ]
