# Generated by Django 6.0.3 on 2026-04-19 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0034_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Leave blank for global/platform categories. Set for store-specific categories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='parlour.store'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'store'), name='unique_category_per_store'),
        ),
    ]
